//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventInvitee
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        public int OrganizationId { get; set; }
        public int UserId { get; set; }
        public System.DateTime NotificationSentOn { get; set; }
        public Nullable<int> RSVPId { get; set; }
        public Nullable<System.DateTime> RSVPDateTime { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual RSVPMaster RSVPMaster { get; set; }
        public virtual User User { get; set; }
    }
}
