//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilityCancellation
    {
        public int FacilityBookingId { get; set; }
        public int OrganizationId { get; set; }
        public System.DateTime CanceledOn { get; set; }
        public int CanceledBy { get; set; }
        public string Reason { get; set; }
    
        public virtual FacilityBooking FacilityBooking { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
