//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SportsSiteEntities : DbContext
    {
        public SportsSiteEntities()
            : base("name=SportsSiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CityStateZip> CityStateZips { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventAddress> EventAddresses { get; set; }
        public virtual DbSet<EventComment> EventComments { get; set; }
        public virtual DbSet<EventInvitee> EventInvitees { get; set; }
        public virtual DbSet<EventMedia> EventMedias { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<Facility> Facilities { get; set; }
        public virtual DbSet<FacilityBooking> FacilityBookings { get; set; }
        public virtual DbSet<FacilityBookingStatu> FacilityBookingStatus { get; set; }
        public virtual DbSet<FacilityBookingUnitType> FacilityBookingUnitTypes { get; set; }
        public virtual DbSet<FacilityCancellation> FacilityCancellations { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<League> Leagues { get; set; }
        public virtual DbSet<MatchResult> MatchResults { get; set; }
        public virtual DbSet<MediaComment> MediaComments { get; set; }
        public virtual DbSet<MediaType> MediaTypes { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<NotificationStatu> NotificationStatus { get; set; }
        public virtual DbSet<NotificationType> NotificationTypes { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<RSVPMaster> RSVPMasters { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<SkillSpeciality> SkillSpecialities { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<TeamManagement> TeamManagements { get; set; }
        public virtual DbSet<TeamMember> TeamMembers { get; set; }
        public virtual DbSet<TeamTitle> TeamTitles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<Year> Years { get; set; }
    
        public virtual int AddEvent(ObjectParameter id, string name, string description, Nullable<int> hostId, Nullable<int> typeId, Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime, Nullable<int> homeTeamId, Nullable<int> visitorTeamId, Nullable<int> createdBy)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var hostIdParameter = hostId.HasValue ?
                new ObjectParameter("HostId", hostId) :
                new ObjectParameter("HostId", typeof(int));
    
            var typeIdParameter = typeId.HasValue ?
                new ObjectParameter("TypeId", typeId) :
                new ObjectParameter("TypeId", typeof(int));
    
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("StartTime", startTime) :
                new ObjectParameter("StartTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.DateTime));
    
            var homeTeamIdParameter = homeTeamId.HasValue ?
                new ObjectParameter("HomeTeamId", homeTeamId) :
                new ObjectParameter("HomeTeamId", typeof(int));
    
            var visitorTeamIdParameter = visitorTeamId.HasValue ?
                new ObjectParameter("VisitorTeamId", visitorTeamId) :
                new ObjectParameter("VisitorTeamId", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddEvent", id, nameParameter, descriptionParameter, hostIdParameter, typeIdParameter, startTimeParameter, endTimeParameter, homeTeamIdParameter, visitorTeamIdParameter, createdByParameter);
        }
    
        public virtual int DeleteEvent(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteEvent", idParameter);
        }
    
        public virtual int DeleteEventMedia(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteEventMedia", idParameter);
        }
    
        public virtual int DeleteMediaComments(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteMediaComments", idParameter);
        }
    
        public virtual int DeleteTeam(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteTeam", idParameter);
        }
    
        public virtual int DeleteTeamManagement(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteTeamManagement", idParameter);
        }
    
        public virtual int DeleteTeamMember(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteTeamMember", idParameter);
        }
    
        public virtual ObjectResult<GetEvent_Result> GetEvent(Nullable<int> id, Nullable<int> organizationId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEvent_Result>("GetEvent", idParameter, organizationIdParameter);
        }
    
        public virtual ObjectResult<GetEventAddresses_Result> GetEventAddresses(Nullable<int> eventId, Nullable<int> organizationId)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("EventId", eventId) :
                new ObjectParameter("EventId", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEventAddresses_Result>("GetEventAddresses", eventIdParameter, organizationIdParameter);
        }
    
        public virtual ObjectResult<GetEventComments_Result> GetEventComments(Nullable<int> eventId, Nullable<int> organizationId)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("EventId", eventId) :
                new ObjectParameter("EventId", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEventComments_Result>("GetEventComments", eventIdParameter, organizationIdParameter);
        }
    
        public virtual ObjectResult<GetEventInviteeByUserId_Result> GetEventInviteeByUserId(Nullable<int> eventId, Nullable<int> userId, Nullable<int> organizationId)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("EventId", eventId) :
                new ObjectParameter("EventId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEventInviteeByUserId_Result>("GetEventInviteeByUserId", eventIdParameter, userIdParameter, organizationIdParameter);
        }
    
        public virtual ObjectResult<GetEventInvitees_Result> GetEventInvitees(Nullable<int> eventId, Nullable<int> organizationId)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("EventId", eventId) :
                new ObjectParameter("EventId", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEventInvitees_Result>("GetEventInvitees", eventIdParameter, organizationIdParameter);
        }
    
        public virtual ObjectResult<GetEventMedia_Result> GetEventMedia(Nullable<int> eventId, Nullable<int> organizationId)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("EventId", eventId) :
                new ObjectParameter("EventId", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEventMedia_Result>("GetEventMedia", eventIdParameter, organizationIdParameter);
        }
    
        public virtual ObjectResult<GetEventMediaById_Result> GetEventMediaById(Nullable<int> id, Nullable<int> organizationId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEventMediaById_Result>("GetEventMediaById", idParameter, organizationIdParameter);
        }
    
        public virtual ObjectResult<GetEventMediaComments_Result> GetEventMediaComments(Nullable<int> mediaId, Nullable<int> organizationId)
        {
            var mediaIdParameter = mediaId.HasValue ?
                new ObjectParameter("MediaId", mediaId) :
                new ObjectParameter("MediaId", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEventMediaComments_Result>("GetEventMediaComments", mediaIdParameter, organizationIdParameter);
        }
    
        public virtual ObjectResult<GetEvents_Result> GetEvents(Nullable<int> organizationId)
        {
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEvents_Result>("GetEvents", organizationIdParameter);
        }
    
        public virtual ObjectResult<GetEventTypeList_Result> GetEventTypeList(Nullable<int> organizationId)
        {
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEventTypeList_Result>("GetEventTypeList", organizationIdParameter);
        }
    
        public virtual ObjectResult<GetListItems_Result> GetListItems(Nullable<int> listId, Nullable<int> organizationId)
        {
            var listIdParameter = listId.HasValue ?
                new ObjectParameter("ListId", listId) :
                new ObjectParameter("ListId", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetListItems_Result>("GetListItems", listIdParameter, organizationIdParameter);
        }
    
        public virtual ObjectResult<GetOrganization_Result> GetOrganization(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrganization_Result>("GetOrganization", idParameter);
        }
    
        public virtual ObjectResult<GetRSVPCount_Result> GetRSVPCount(Nullable<int> eventId, Nullable<int> organizationId)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("EventId", eventId) :
                new ObjectParameter("EventId", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRSVPCount_Result>("GetRSVPCount", eventIdParameter, organizationIdParameter);
        }
    
        public virtual ObjectResult<GetRSVPList_Result> GetRSVPList(Nullable<int> organizationId)
        {
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRSVPList_Result>("GetRSVPList", organizationIdParameter);
        }
    
        public virtual ObjectResult<GetTeam_Result> GetTeam(Nullable<int> id, Nullable<int> organizationId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTeam_Result>("GetTeam", idParameter, organizationIdParameter);
        }
    
        public virtual ObjectResult<GetTeamList_Result> GetTeamList(Nullable<int> organizationId)
        {
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTeamList_Result>("GetTeamList", organizationIdParameter);
        }
    
        public virtual ObjectResult<GetTeamManagement_Result> GetTeamManagement(Nullable<int> teamId, Nullable<int> organizationId)
        {
            var teamIdParameter = teamId.HasValue ?
                new ObjectParameter("TeamId", teamId) :
                new ObjectParameter("TeamId", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTeamManagement_Result>("GetTeamManagement", teamIdParameter, organizationIdParameter);
        }
    
        public virtual ObjectResult<GetTeamMember_Result> GetTeamMember(Nullable<int> id, Nullable<int> organizationId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTeamMember_Result>("GetTeamMember", idParameter, organizationIdParameter);
        }
    
        public virtual ObjectResult<GetTeamMemberByTeam_Result> GetTeamMemberByTeam(Nullable<int> teamId, Nullable<int> organizationId)
        {
            var teamIdParameter = teamId.HasValue ?
                new ObjectParameter("TeamId", teamId) :
                new ObjectParameter("TeamId", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTeamMemberByTeam_Result>("GetTeamMemberByTeam", teamIdParameter, organizationIdParameter);
        }
    
        public virtual ObjectResult<GetTeams_Result> GetTeams(Nullable<int> organizationId)
        {
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTeams_Result>("GetTeams", organizationIdParameter);
        }
    
        public virtual ObjectResult<GetTeamTitleList_Result> GetTeamTitleList(Nullable<int> organizationId)
        {
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTeamTitleList_Result>("GetTeamTitleList", organizationIdParameter);
        }
    
        public virtual ObjectResult<GetUser_Result> GetUser(Nullable<int> id, Nullable<int> organizationId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUser_Result>("GetUser", idParameter, organizationIdParameter);
        }
    
        public virtual ObjectResult<GetUserByEmailId_Result> GetUserByEmailId(string emailId, Nullable<int> organizationId)
        {
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserByEmailId_Result>("GetUserByEmailId", emailIdParameter, organizationIdParameter);
        }
    
        public virtual ObjectResult<GetUserList_Result> GetUserList(Nullable<int> organizationId)
        {
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserList_Result>("GetUserList", organizationIdParameter);
        }
    
        public virtual ObjectResult<GetUserListByRSVP_Result> GetUserListByRSVP(Nullable<int> eventId, Nullable<int> rSVPId, Nullable<int> organizationId)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("EventId", eventId) :
                new ObjectParameter("EventId", typeof(int));
    
            var rSVPIdParameter = rSVPId.HasValue ?
                new ObjectParameter("RSVPId", rSVPId) :
                new ObjectParameter("RSVPId", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserListByRSVP_Result>("GetUserListByRSVP", eventIdParameter, rSVPIdParameter, organizationIdParameter);
        }
    
        public virtual int SaveEvent(ObjectParameter id, Nullable<int> organizationId, string name, string description, Nullable<int> hostId, Nullable<int> typeId, Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime, Nullable<int> homeTeamId, Nullable<int> visitorTeamId, string contactPhoneNumber1, string contactPhoneNumber2, Nullable<int> createdBy, Nullable<int> modifiedBy, Nullable<System.DateTime> modifiedOn)
        {
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var hostIdParameter = hostId.HasValue ?
                new ObjectParameter("HostId", hostId) :
                new ObjectParameter("HostId", typeof(int));
    
            var typeIdParameter = typeId.HasValue ?
                new ObjectParameter("TypeId", typeId) :
                new ObjectParameter("TypeId", typeof(int));
    
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("StartTime", startTime) :
                new ObjectParameter("StartTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.DateTime));
    
            var homeTeamIdParameter = homeTeamId.HasValue ?
                new ObjectParameter("HomeTeamId", homeTeamId) :
                new ObjectParameter("HomeTeamId", typeof(int));
    
            var visitorTeamIdParameter = visitorTeamId.HasValue ?
                new ObjectParameter("VisitorTeamId", visitorTeamId) :
                new ObjectParameter("VisitorTeamId", typeof(int));
    
            var contactPhoneNumber1Parameter = contactPhoneNumber1 != null ?
                new ObjectParameter("ContactPhoneNumber1", contactPhoneNumber1) :
                new ObjectParameter("ContactPhoneNumber1", typeof(string));
    
            var contactPhoneNumber2Parameter = contactPhoneNumber2 != null ?
                new ObjectParameter("ContactPhoneNumber2", contactPhoneNumber2) :
                new ObjectParameter("ContactPhoneNumber2", typeof(string));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var modifiedByParameter = modifiedBy.HasValue ?
                new ObjectParameter("ModifiedBy", modifiedBy) :
                new ObjectParameter("ModifiedBy", typeof(int));
    
            var modifiedOnParameter = modifiedOn.HasValue ?
                new ObjectParameter("ModifiedOn", modifiedOn) :
                new ObjectParameter("ModifiedOn", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveEvent", id, organizationIdParameter, nameParameter, descriptionParameter, hostIdParameter, typeIdParameter, startTimeParameter, endTimeParameter, homeTeamIdParameter, visitorTeamIdParameter, contactPhoneNumber1Parameter, contactPhoneNumber2Parameter, createdByParameter, modifiedByParameter, modifiedOnParameter);
        }
    
        public virtual int SaveEventAddress(ObjectParameter id, ObjectParameter eventId, string organizationId, string street1, string street2, string city, string state, string zipCd, string landMark)
        {
            var organizationIdParameter = organizationId != null ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(string));
    
            var street1Parameter = street1 != null ?
                new ObjectParameter("Street1", street1) :
                new ObjectParameter("Street1", typeof(string));
    
            var street2Parameter = street2 != null ?
                new ObjectParameter("Street2", street2) :
                new ObjectParameter("Street2", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(string));
    
            var zipCdParameter = zipCd != null ?
                new ObjectParameter("ZipCd", zipCd) :
                new ObjectParameter("ZipCd", typeof(string));
    
            var landMarkParameter = landMark != null ?
                new ObjectParameter("LandMark", landMark) :
                new ObjectParameter("LandMark", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveEventAddress", id, eventId, organizationIdParameter, street1Parameter, street2Parameter, cityParameter, stateParameter, zipCdParameter, landMarkParameter);
        }
    
        public virtual int SaveEventComment(ObjectParameter id, Nullable<int> organizationId, Nullable<int> eventId, string eventComments, string mediaPath, Nullable<int> parentCommentId, Nullable<int> createdBy, Nullable<int> modifiedBy)
        {
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("EventId", eventId) :
                new ObjectParameter("EventId", typeof(int));
    
            var eventCommentsParameter = eventComments != null ?
                new ObjectParameter("EventComments", eventComments) :
                new ObjectParameter("EventComments", typeof(string));
    
            var mediaPathParameter = mediaPath != null ?
                new ObjectParameter("MediaPath", mediaPath) :
                new ObjectParameter("MediaPath", typeof(string));
    
            var parentCommentIdParameter = parentCommentId.HasValue ?
                new ObjectParameter("ParentCommentId", parentCommentId) :
                new ObjectParameter("ParentCommentId", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var modifiedByParameter = modifiedBy.HasValue ?
                new ObjectParameter("ModifiedBy", modifiedBy) :
                new ObjectParameter("ModifiedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveEventComment", id, organizationIdParameter, eventIdParameter, eventCommentsParameter, mediaPathParameter, parentCommentIdParameter, createdByParameter, modifiedByParameter);
        }
    
        public virtual int SaveEventInvitee(ObjectParameter id, Nullable<int> eventId, Nullable<int> organizationId, Nullable<int> userId, string emailId, Nullable<System.DateTime> notificationSentOn)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("EventId", eventId) :
                new ObjectParameter("EventId", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            var notificationSentOnParameter = notificationSentOn.HasValue ?
                new ObjectParameter("NotificationSentOn", notificationSentOn) :
                new ObjectParameter("NotificationSentOn", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveEventInvitee", id, eventIdParameter, organizationIdParameter, userIdParameter, emailIdParameter, notificationSentOnParameter);
        }
    
        public virtual int SaveEventMedia(ObjectParameter id, Nullable<int> eventId, Nullable<int> organizationId, string mediaName, string mediaPath, Nullable<int> mediaTypeId, Nullable<int> createdBy, Nullable<int> modifiedBy)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("EventId", eventId) :
                new ObjectParameter("EventId", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            var mediaNameParameter = mediaName != null ?
                new ObjectParameter("MediaName", mediaName) :
                new ObjectParameter("MediaName", typeof(string));
    
            var mediaPathParameter = mediaPath != null ?
                new ObjectParameter("MediaPath", mediaPath) :
                new ObjectParameter("MediaPath", typeof(string));
    
            var mediaTypeIdParameter = mediaTypeId.HasValue ?
                new ObjectParameter("MediaTypeId", mediaTypeId) :
                new ObjectParameter("MediaTypeId", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var modifiedByParameter = modifiedBy.HasValue ?
                new ObjectParameter("ModifiedBy", modifiedBy) :
                new ObjectParameter("ModifiedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveEventMedia", id, eventIdParameter, organizationIdParameter, mediaNameParameter, mediaPathParameter, mediaTypeIdParameter, createdByParameter, modifiedByParameter);
        }
    
        public virtual int SaveMediaComment(ObjectParameter id, Nullable<int> organizationId, Nullable<int> mediaId, string comments, Nullable<int> commentedBy, Nullable<int> modifiedBy)
        {
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            var mediaIdParameter = mediaId.HasValue ?
                new ObjectParameter("MediaId", mediaId) :
                new ObjectParameter("MediaId", typeof(int));
    
            var commentsParameter = comments != null ?
                new ObjectParameter("Comments", comments) :
                new ObjectParameter("Comments", typeof(string));
    
            var commentedByParameter = commentedBy.HasValue ?
                new ObjectParameter("CommentedBy", commentedBy) :
                new ObjectParameter("CommentedBy", typeof(int));
    
            var modifiedByParameter = modifiedBy.HasValue ?
                new ObjectParameter("ModifiedBy", modifiedBy) :
                new ObjectParameter("ModifiedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveMediaComment", id, organizationIdParameter, mediaIdParameter, commentsParameter, commentedByParameter, modifiedByParameter);
        }
    
        public virtual int SaveRSVP(Nullable<int> eventId, Nullable<int> userId, Nullable<int> rSVPId, Nullable<int> organizationId)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("EventId", eventId) :
                new ObjectParameter("EventId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var rSVPIdParameter = rSVPId.HasValue ?
                new ObjectParameter("RSVPId", rSVPId) :
                new ObjectParameter("RSVPId", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveRSVP", eventIdParameter, userIdParameter, rSVPIdParameter, organizationIdParameter);
        }
    
        public virtual int SaveTeam(string name, Nullable<int> organizationId, string nickname, string description, string photoUrl, Nullable<int> createdBy, Nullable<int> modifiedBy, ObjectParameter id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            var nicknameParameter = nickname != null ?
                new ObjectParameter("Nickname", nickname) :
                new ObjectParameter("Nickname", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var photoUrlParameter = photoUrl != null ?
                new ObjectParameter("PhotoUrl", photoUrl) :
                new ObjectParameter("PhotoUrl", typeof(string));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var modifiedByParameter = modifiedBy.HasValue ?
                new ObjectParameter("ModifiedBy", modifiedBy) :
                new ObjectParameter("ModifiedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveTeam", nameParameter, organizationIdParameter, nicknameParameter, descriptionParameter, photoUrlParameter, createdByParameter, modifiedByParameter, id);
        }
    
        public virtual int SaveTeamManagement(Nullable<int> teamid, Nullable<int> organizationId, Nullable<int> titleid, Nullable<int> teammemberid, Nullable<int> createdBy, Nullable<int> modifiedBy, ObjectParameter id)
        {
            var teamidParameter = teamid.HasValue ?
                new ObjectParameter("Teamid", teamid) :
                new ObjectParameter("Teamid", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            var titleidParameter = titleid.HasValue ?
                new ObjectParameter("Titleid", titleid) :
                new ObjectParameter("Titleid", typeof(int));
    
            var teammemberidParameter = teammemberid.HasValue ?
                new ObjectParameter("Teammemberid", teammemberid) :
                new ObjectParameter("Teammemberid", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var modifiedByParameter = modifiedBy.HasValue ?
                new ObjectParameter("ModifiedBy", modifiedBy) :
                new ObjectParameter("ModifiedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveTeamManagement", teamidParameter, organizationIdParameter, titleidParameter, teammemberidParameter, createdByParameter, modifiedByParameter, id);
        }
    
        public virtual int SaveTeamMember(Nullable<int> teamid, Nullable<int> organizationId, string name, string nickname, Nullable<int> skillSpecialityId, Nullable<System.DateTime> birthday, string placeofbirth, Nullable<int> livedinUSAsince, string schoolname, string grade, string battingstyle, string favshot, string bowlingstyle, string favcricketer, string likes, string dislikes, string favfood, string favmovie, string aim, string hobbies, string photoUrl, Nullable<int> createdBy, Nullable<int> modifiedBy, ObjectParameter id)
        {
            var teamidParameter = teamid.HasValue ?
                new ObjectParameter("Teamid", teamid) :
                new ObjectParameter("Teamid", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var nicknameParameter = nickname != null ?
                new ObjectParameter("Nickname", nickname) :
                new ObjectParameter("Nickname", typeof(string));
    
            var skillSpecialityIdParameter = skillSpecialityId.HasValue ?
                new ObjectParameter("SkillSpecialityId", skillSpecialityId) :
                new ObjectParameter("SkillSpecialityId", typeof(int));
    
            var birthdayParameter = birthday.HasValue ?
                new ObjectParameter("Birthday", birthday) :
                new ObjectParameter("Birthday", typeof(System.DateTime));
    
            var placeofbirthParameter = placeofbirth != null ?
                new ObjectParameter("Placeofbirth", placeofbirth) :
                new ObjectParameter("Placeofbirth", typeof(string));
    
            var livedinUSAsinceParameter = livedinUSAsince.HasValue ?
                new ObjectParameter("LivedinUSAsince", livedinUSAsince) :
                new ObjectParameter("LivedinUSAsince", typeof(int));
    
            var schoolnameParameter = schoolname != null ?
                new ObjectParameter("Schoolname", schoolname) :
                new ObjectParameter("Schoolname", typeof(string));
    
            var gradeParameter = grade != null ?
                new ObjectParameter("Grade", grade) :
                new ObjectParameter("Grade", typeof(string));
    
            var battingstyleParameter = battingstyle != null ?
                new ObjectParameter("Battingstyle", battingstyle) :
                new ObjectParameter("Battingstyle", typeof(string));
    
            var favshotParameter = favshot != null ?
                new ObjectParameter("Favshot", favshot) :
                new ObjectParameter("Favshot", typeof(string));
    
            var bowlingstyleParameter = bowlingstyle != null ?
                new ObjectParameter("Bowlingstyle", bowlingstyle) :
                new ObjectParameter("Bowlingstyle", typeof(string));
    
            var favcricketerParameter = favcricketer != null ?
                new ObjectParameter("Favcricketer", favcricketer) :
                new ObjectParameter("Favcricketer", typeof(string));
    
            var likesParameter = likes != null ?
                new ObjectParameter("Likes", likes) :
                new ObjectParameter("Likes", typeof(string));
    
            var dislikesParameter = dislikes != null ?
                new ObjectParameter("Dislikes", dislikes) :
                new ObjectParameter("Dislikes", typeof(string));
    
            var favfoodParameter = favfood != null ?
                new ObjectParameter("Favfood", favfood) :
                new ObjectParameter("Favfood", typeof(string));
    
            var favmovieParameter = favmovie != null ?
                new ObjectParameter("Favmovie", favmovie) :
                new ObjectParameter("Favmovie", typeof(string));
    
            var aimParameter = aim != null ?
                new ObjectParameter("Aim", aim) :
                new ObjectParameter("Aim", typeof(string));
    
            var hobbiesParameter = hobbies != null ?
                new ObjectParameter("Hobbies", hobbies) :
                new ObjectParameter("Hobbies", typeof(string));
    
            var photoUrlParameter = photoUrl != null ?
                new ObjectParameter("PhotoUrl", photoUrl) :
                new ObjectParameter("PhotoUrl", typeof(string));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var modifiedByParameter = modifiedBy.HasValue ?
                new ObjectParameter("ModifiedBy", modifiedBy) :
                new ObjectParameter("ModifiedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveTeamMember", teamidParameter, organizationIdParameter, nameParameter, nicknameParameter, skillSpecialityIdParameter, birthdayParameter, placeofbirthParameter, livedinUSAsinceParameter, schoolnameParameter, gradeParameter, battingstyleParameter, favshotParameter, bowlingstyleParameter, favcricketerParameter, likesParameter, dislikesParameter, favfoodParameter, favmovieParameter, aimParameter, hobbiesParameter, photoUrlParameter, createdByParameter, modifiedByParameter, id);
        }
    
        public virtual int SaveUser(ObjectParameter id, Nullable<int> organizationId, Nullable<int> userTypeId, string firstName, string lastName, string emailId, string password, Nullable<int> genderId, string profilePhotoPath)
        {
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            var userTypeIdParameter = userTypeId.HasValue ?
                new ObjectParameter("UserTypeId", userTypeId) :
                new ObjectParameter("UserTypeId", typeof(int));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var genderIdParameter = genderId.HasValue ?
                new ObjectParameter("GenderId", genderId) :
                new ObjectParameter("GenderId", typeof(int));
    
            var profilePhotoPathParameter = profilePhotoPath != null ?
                new ObjectParameter("ProfilePhotoPath", profilePhotoPath) :
                new ObjectParameter("ProfilePhotoPath", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveUser", id, organizationIdParameter, userTypeIdParameter, firstNameParameter, lastNameParameter, emailIdParameter, passwordParameter, genderIdParameter, profilePhotoPathParameter);
        }
    
        public virtual int UpdateEvent(ObjectParameter id, string name, string description, Nullable<int> hostId, Nullable<int> typeId, Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime, Nullable<int> homeTeamId, Nullable<int> visitorTeamId, Nullable<int> createdBy, Nullable<int> modifiedBy, Nullable<System.DateTime> modifiedOn)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var hostIdParameter = hostId.HasValue ?
                new ObjectParameter("HostId", hostId) :
                new ObjectParameter("HostId", typeof(int));
    
            var typeIdParameter = typeId.HasValue ?
                new ObjectParameter("TypeId", typeId) :
                new ObjectParameter("TypeId", typeof(int));
    
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("StartTime", startTime) :
                new ObjectParameter("StartTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.DateTime));
    
            var homeTeamIdParameter = homeTeamId.HasValue ?
                new ObjectParameter("HomeTeamId", homeTeamId) :
                new ObjectParameter("HomeTeamId", typeof(int));
    
            var visitorTeamIdParameter = visitorTeamId.HasValue ?
                new ObjectParameter("VisitorTeamId", visitorTeamId) :
                new ObjectParameter("VisitorTeamId", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var modifiedByParameter = modifiedBy.HasValue ?
                new ObjectParameter("ModifiedBy", modifiedBy) :
                new ObjectParameter("ModifiedBy", typeof(int));
    
            var modifiedOnParameter = modifiedOn.HasValue ?
                new ObjectParameter("ModifiedOn", modifiedOn) :
                new ObjectParameter("ModifiedOn", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateEvent", id, nameParameter, descriptionParameter, hostIdParameter, typeIdParameter, startTimeParameter, endTimeParameter, homeTeamIdParameter, visitorTeamIdParameter, createdByParameter, modifiedByParameter, modifiedOnParameter);
        }
    }
}
